apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stocksplat-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: stocksplat-service
            port:
              number: 8080
